import type { ThemeDefinition } from 'vuetify';

export const myCustomLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    background: '#ffffff',
    surface: '#f3f3f3',
    'surface-bright': '#e4e4e4',
    'surface-light': '#ffffff',
    'surface-variant': '#bfbfbf',
    'on-surface-variant': '#EEE',
    primary: '#000000',
    'primary-lighten-1': '#4e4e4e',
    'primary-darken-1': '#001f25',
    secondary: '#f2df73',
    'secondary-darken-1': '#bfb05a',
    error: '#B00020',
    info: '#007b9c',
    success: '#4CAF50',
    warning: '#FB8C00',
  },
  variables: {
    'idle-opacity': 0.04,
    'hover-opacity': 0.04,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#212529',
    'theme-on-kbd': '#FFFFFF',
    'theme-code': '#F5F5F5',
    'theme-on-code': '#000000',
  },
};
