import type { ThemeDefinition } from 'vuetify';

export const myCustomLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    background: '#F2EBDD',
    'on-background': '#2A231B',
    surface: '#FFF9EE',
    'surface-variant': '#D8CBB8',
    'on-surface': '#302820',
    'on-surface-variant': '#675A4A',
    primary: '#8A5C25',
    'primary-lighten-1': '#AD7838',
    'primary-darken-1': '#523719',
    'on-primary': '#FFF9EE',
    'on-primary-darken-1': '#FFF9EE',
    secondary: '#5B4935',
    'secondary-lighten-1': '#806A50',
    'secondary-darken-1': '#352A20',
    'on-secondary': '#FFF9EE',
    error: '#A63D36',
    info: '#665A46',
    success: '#4F7347',
    warning: '#9A651F',
  },
  variables: {
    'border-opacity': 0.2,
    'border-radius': '4px',
    'border-button-radius': '2px',
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.7,
    'disabled-opacity': 0.45,
    'idle-opacity': 0.04,
    'hover-opacity': 0.12,
    'focus-opacity': 0.2,
    'selected-opacity': 0.14,
    'activated-opacity': 0.18,
    'pressed-opacity': 0.22,
    'dragged-opacity': 0.08,
  },
};

export const myCustomGoldTheme: ThemeDefinition = {
  dark: true,
  colors: {
    background: '#151515',
    'on-background': '#F4E8D3',
    surface: '#171614',
    'surface-variant': '#332F29',
    'on-surface': '#EEE5D6',
    'on-surface-variant': '#CFC2AF',
    primary: '#C89B5C',
    'primary-lighten-1': '#E7C796',
    'primary-darken-1': '#785630',
    'on-primary': '#17110A',
    'on-primary-darken-1': '#FFF7E8',
    secondary: '#EAD7B5',
    'secondary-lighten-1': '#FFF1D2',
    'secondary-darken-1': '#A98351',
    'on-secondary': '#17110A',
    error: '#D96B62',
    info: '#B9A57E',
    success: '#8EAD82',
    warning: '#DDAE67',
  },
  variables: {
    'border-opacity': 0.2,
    'border-radius': '4px',
    'border-button-radius': '2px',
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.7,
    'disabled-opacity': 0.45,
    'idle-opacity': 0.04,
    'hover-opacity': 0.12,
    'focus-opacity': 0.2,
    'selected-opacity': 0.14,
    'activated-opacity': 0.18,
    'pressed-opacity': 0.22,
    'dragged-opacity': 0.08,
  },
};
