import type { ThemeDefinition } from 'vuetify';

export const myCustomLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    background: '#FFFFFF',
    'on-background': '#1F1F1F',
    surface: '#efefef',
    'surface-variant': '#EAEAEA',
    'on-surface-variant': '#424242',
    primary: '#670b24',
    'primary-lighten-1': '#8d0f31',
    'primary-darken-1': '#340512',
    'on-primary': '#94CA59',
    secondary: '#94CA59',
    'secondary-lighten-1': '#B2E07F',
    'secondary-darken-1': '#6FA83F',
    'on-secondary': '#670b24',
    error: '#B00020',
    info: '#007b9c',
    success: '#4CAF50',
    warning: '#FB8C00',
  },
  variables: {
    'border-opacity': 0.2,
    'border-radius': '16px',
    'border-button-radius': '18px',
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.7,
    'disabled-opacity': 0.45,
    'idle-opacity': 0.04,
    'hover-opacity': 0.12,
    'focus-opacity': 0.2,
    'selected-opacity': 0.14,
    'activated-opacity': 0.18,
    'pressed-opacity': 0.22,
    'dragged-opacity': 0.08,
  },
};

export const myCustomGoldTheme: ThemeDefinition = {
  dark: true,
  colors: {
    background: '#2c2927',
    'on-background': '#db892f',
    surface: '#ccc5b4',
    'surface-variant': '#8a866c',
    'on-surface': '#393632',
    primary: '#b98913',
    'primary-lighten-1': '#ffbc1a',
    'primary-darken-1': '#6c500b',
    'on-primary': '#050503',
    secondary: '#050503',
    'secondary-lighten-1': '#222215',
    'secondary-darken-1': '#000000',
    'on-secondary': '#b98913',

  },
  variables: {
    'border-opacity': 0.2,
    'border-radius': '16px',
    'border-button-radius': '18px',
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.7,
    'disabled-opacity': 0.45,
    'idle-opacity': 0.04,
    'hover-opacity': 0.12,
    'focus-opacity': 0.2,
    'selected-opacity': 0.14,
    'activated-opacity': 0.18,
    'pressed-opacity': 0.22,
    'dragged-opacity': 0.08,
  },
};
